package com.lumiring.updateManager.domain.constant;

public enum Code {
    REQUEST_VALIDATION_ERROR,
    NOT_FOUND,
    BAD_CREDENTIALS,
    JWT_EXPIRED,
    USERNAME_BUSY,
    INTERNAL_SERVER_ERROR,
    USER_NOT_FOUND,
    AUTHORIZATION_ERROR,
    MISSING_REQUEST_HEADER,
    NOT_READABLE,
    SUBSCRIPTION_LOGIC_ERROR,
    PUBLISHER_NOT_FOUND,
    ALREADY_SUBSCRIBED,
    NOT_SUPPORTED,
    NOT_BLOCK_YOURSELF,
    BLOCKED,
    TEST
}
